### ISSUE TITLE
VlcInstance problem

### ISSUE THREAD

**Issue by camelcoding** [ntadej/vlc-qt#31]
Hello first of all im not sure if this a problem of my configuration or of the vlc-qt library.

My problem is if i open one single Window with videoWidget the x Server is still okay but if i open more than one Window the Xorg has a very high CPU load. If i do the same thing with Vlc there is no such problem.

I checked my Vlc configuration and realized that there is the accelerate graphics is checked and the video out put is set to OpenGL GLX video output (xcb). So I tried to check the --vout=xcb_glx option and put that into the VlcInstance constructor -> the performance is still bad.
I tried than to set --vout=caca - the picture is still shown normal (the Output should be video with colored text instead of the image).

Any solutions?

Thank you very much!

**Comment by camelcoding** [comment]
Its OK it was a problem with the graphics driver

**Comment by manik005** [comment]
hey @camelcoding by any chance do you remember the resolution for this issue ?
