### ISSUE TITLE
Qt4::Core and Qt4::Gui not found on MacOSX 10.10

### ISSUE THREAD

**Issue by kfieldi5** [ntadej/vlc-qt#59]
I am trying to get your vlc-qt project to work for Qt4 currently (plan to also use it in my Qt5 environment once I get 4 working).

I modified CMakeLists.txt to SET(QT_VERSION 4) if QT_VERSION is not defined. That got me to where I am now.

I installed Qt4.8.6 via homebrew so it is in /usr/local/Cellar/qt/4.8.6 ...

Any help would be appreciated, here is output:

kevinbook:build kevin$ cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..
VLC-Qt: Build with Qt4
VLC-Qt: Build with Widgets: ON
VLC-Qt: Build statically: OFF
-- Found LibVLC include-dir path: /Applications/VLC.app/Contents/MacOS/include
-- Found LibVLC library path:/usr/local/lib/libvlc.dylib
-- Found LibVLCcore library path:/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib

VLC-Qt: You are compiling libvlc-qt 0.10.0

-- Git Version Patch: 3488d87

VLC-Qt: Build tests: OFF

-- Configuring done
CMake Error at src/core/CMakeLists.txt:124 (ADD_LIBRARY):
  Target "vlc-qt" links to target "Qt4::Core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at src/widgets/CMakeLists.txt:96 (ADD_LIBRARY):
  Target "vlc-qt-widgets" links to target "Qt4::Gui" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /Users/kevin/vlc-qt/build
kevinbook:build kevin$

**Comment by v-fox** [comment]
I don't think that it's a mac issue. Got the same thing on OpenBuildService of openSUSE 13.2.

**Comment by ntadej** [comment]
Yes, there seems to be cmake change that breaks this. Will fix.
