### ISSUE TITLE
Building vlc-qt on Windows. Can't find LibVLC!

### ISSUE THREAD

**Issue by kfieldi5** [ntadej/vlc-qt#65]
I am having an issue with LIBVLC not being found when trying to build and install on Windows.

In the FindLIBVLC.cmake file I have added under the include paths list:

"C:/Program Files (x86)/VideoLAN/VLC/sdk/include/vlc"

And in the libvlc paths lists:

"C:/Program Files (x86)/VideoLAN/VLC"
"C:/Program Files (x86)/VideoLAN/VLC/plugins"

I believe these are the correct paths, but still I get "Error could not find LibVLC" from running the cmake .. 

I tried with backslashes instead of forward slashes but that results in a cmake parsing error.

Please help!

Love,
Kevin

**Comment by ntadej** [comment]
This works for me with current master. Note that current VLC 2.2.1 has incomplete SDK with the installer. Use the zip from the download mirror.
