### ISSUE TITLE
vlc-qt libraries not working in Qt 5 in Ubuntu 14.04

### ISSUE THREAD

**Issue by manojpatidar** [ntadej/vlc-qt#69]
At my end vlc-qt libraries working in Qt 4.8.6 but not working in Qt 5 in Ubuntu 14.04.

In Qt5 vlc-qt libraries compiled successfully but getting crashed while run the project into Qt5 in Ubuntu 14.04. Can anyone help me in this ?

Thanks.

**Comment by ntadej** [comment]
This is a packaging bug. Use the VLC build provided in my PPA or build your own with patch here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755154

**Comment by manojpatidar** [comment]
@ntadej , "Use the VLC build provided in my PPA or build your own with patch here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755154" 
How  can I use vlc build which is provided in your PPA, Can you please describe me in detail ?
Is it possible to build vlc-qt libs in QT5 in Ubuntu 14.04 ?

**Comment by manojpatidar** [comment]
@ntadej <https://github.com/ntadej> , "Use the VLC build provided in my PPA
or build your own with patch here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755154"
How can I use vlc build which is provided in your PPA, Can you please
describe me in detail ?
Is it possible to build vlc-qt libs in QT5 in Ubuntu 14.04 ?

Thanks & Regards,
Mnaoj Patidar
