### ISSUE TITLE
MSVC2013 release?

### ISSUE THREAD

**Issue by maximus321** [ntadej/vlc-qt#71]
I would really like if a MSVC2013 version could be released on the site.
Here is the previous thread containing a solution :
https://github.com/ntadej/vlc-qt/issues/43

MSVC2013 is a must if you need to use QWebEngine on windows using Qt 5.4
Thank you!

**Comment by ntadej** [comment]
Hopefully this weekend with VLC 2.2 and Qt 5.5.1.

**Comment by MBach** [comment]
Great ! Looking forward to see the next release :)

**Comment by maximus321** [comment]
Hey ntadej let me know if I can give you an hand with something, thanks

**Comment by ntadej** [comment]
Sorry for the delay. It should be ready this weekend as I had some problems with linux packaging.

**Comment by maximus321** [comment]
No hurry, I was able to run it in my compiled MSVC2013 program by installing both the MSVC2012 and MSVC2013 redistributable on my client machine, not perfect but works for now.

**Comment by ntadej** [comment]
Builds will be online tomorrow as I will upload them somewhere with faster internet :)

Redistributables are always needed as far as I know.

**Comment by ntadej** [comment]
Uploaded.
