### ISSUE TITLE
vlc-qt with MinGw, Qt 5.4.1, Windows 7 (x86)

### ISSUE THREAD

**Issue by gavaza** [ntadej/vlc-qt#72]
Hi friends,

Issues when compile vlc-qt with MinGW on Windows 7 (x86).

Regards,

[ 45%] Building CXX object src/core/CMakeFiles/vlc-qt.dir/VideoMemoryStream.cpp.obj
cd /d C:\Users\ef9g\Documents\Nuevo\pacca-code\trunk\vlc-qt\build\src\core && C:\Users\ef9g\Programas\Qt\Qt5.4.1\Tools\mingw491_32\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_EXPORTS @CMakeFiles/vlc-qt.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt.dir\VideoMemoryStream.cpp.obj -c C:\Users\ef9g\Documents\Nuevo\pacca-code\trunk\vlc-qt\src\core\VideoMemoryStream.cpp
In file included from C:/Users/ef9g/Programas/vlc/sdk/include/vlc/plugins/vlc_common.h:417:0,
                 from C:/Users/ef9g/Programas/vlc/sdk/include/vlc/plugins/vlc_fourcc.h:27,
                 from C:/Users/ef9g/Documents/Nuevo/pacca-code/trunk/vlc-qt/src/core/VideoMemoryStream.h:28,
                 from C:\Users\ef9g\Documents\Nuevo\pacca-code\trunk\vlc-qt\src\core\VideoMemoryStream.cpp:25:
C:/Users/ef9g/Programas/vlc/sdk/include/vlc/plugins/vlc_threads.h: In function 'int vlc_poll(pollfd*, unsigned int, int)':
C:/Users/ef9g/Programas/vlc/sdk/include/vlc/plugins/vlc_threads.h:424:44: error: 'poll' was not declared in this scope
         val = poll (fds, nfds, ugly_timeout);
                                            ^
src\core\CMakeFiles\vlc-qt.dir\build.make:326: recipe for target 'src/core/CMakeFiles/vlc-qt.dir/VideoMemoryStream.cpp.obj' failed
mingw32-make.exe[2]: *** [src/core/CMakeFiles/vlc-qt.dir/VideoMemoryStream.cpp.obj] Error 1
mingw32-make.exe[2]: Leaving directory 'C:/Users/ef9g/Documents/Nuevo/pacca-code/trunk/vlc-qt/build'
CMakeFiles\Makefile2:130: recipe for target 'src/core/CMakeFiles/vlc-qt.dir/all' failed
mingw32-make.exe[1]: *** [src/core/CMakeFiles/vlc-qt.dir/all] Error 2
mingw32-make.exe[1]: Leaving directory 'C:/Users/ef9g/Documents/Nuevo/pacca-code/trunk/vlc-qt/build'
makefile:119: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by gavaza** [comment]
Fixed with manual modification in ${VLC_PATH}/sdk/include/vlc/plugins/vlc_threads.h

+++ ${VLC_PATH}/sdk/include/vlc/plugins/vlc_threads.h
    #if defined (_WIN32)
    # include <process.h>
+  # include <poll.h>
    # ifndef ETIMEDOUT
    #  define ETIMEDOUT 10060 /* This is the value in winsock.h. */
   # endif

**Comment by ntadej** [comment]
There are pre-included patched headers for different VLC versions in windows folder. I haven't tested VLC 2.2 with mingw yet, but 2.1 should be fixed.

**Comment by gavaza** [comment]
Fixed with manual modification in ${VLC_PATH}/sdk/include/vlc/plugins/vlc_threads.h
Included "# include <poll.h>" on first "#if defined (_WIN32)" in file.
